config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'home#welcome', as: 'welcome'
  devise_for :users,
    class_name: 'FormUser',
    controllers: {
      omniauth_callbacks: 'omniauth_callbacks',
      registrations: 'registrations'
    }
  resources :users, only: %i[show index]
  resources :services
  resources :invoices
  resources :communities do
    resources :invitations, only: %i[new create show destroy]
    post 'join/:id', to: 'invitations#join', as: 'join'
  end
end

app/models/invoice.rb
# frozen_string_literal: true

class Invoice < ApplicationRecord
  belongs_to :service
  belongs_to :user
  has_one :period

  scope :current_year, -> { joins(:period).where(['period_start > ?', 1.year.ago]).order('period_start') }
  scope :by_month, ->(month) { joins(:period).where('extract(month from period_start) = ?', month) }

  delegate :name, to: :service, prefix: true
  delegate :single, to: :period
  delegate :period_start, to: :period
  delegate :period_end, to: :period

  validates :service, presence: true
  validates :period, presence: true
  validates :user, presence: true
  validates :price, presence: true, numericality: true

  def single?
    single
  end

  def strf_period
    if single
      "#{I18n.t('periods.single')} #{I18n.l(period_start)}"
    else
      "#{I18n.l(period_start)}...#{I18n.l(period_end)}"
    end
  end

  def self.user_services_by_invoices(invoices)
    Service.where(id: invoices.pluck(:service_id).uniq)
  end

  def self.user_invoices_period_uniq_months(user)
    user.invoices.current_year.pluck(:period_start).map(&:month).uniq
  end

  def self.user_invoices_period_uniq_month_names(months)
    months.each.map { |m| I18n.t('date.abbr_month_names')[m] }
  end

  ### GRAPHS ###
  def self.yearly_summary_graph_data(user)
    user_invoices = user.invoices
    # Different types of services that current user consumes:
    services = Invoice.user_services_by_invoices(user_invoices)
    # last months that user has consumed some services (max 12 months):
    invoice_months = Invoice.user_invoices_period_uniq_months(user)
    # initialize graph x-axis with ticks:
    arr = [['months'] + Invoice.user_invoices_period_uniq_month_names(invoice_months)]
    services.each do |s|
      # all the invoices of certain service (max 12 months the oldest)
      service_invoices = user_invoices.joins(:period).where(service_id: s.id)
      arr << [s.name]
      invoice_months.each do |month|
        # Sum all the prices of current service in current month
        price_sum = service_invoices.by_month(month).sum(:price)
        arr.last << price_sum.to_f
      end
    end
    arr.transpose # data-matrix for google charts ready
  end
  ### END OF GRAPHS ###
end

app/controllers/invoices_controller.rb
# frozen_string_literal: true

class InvoicesController < ApplicationController
  before_action :set_invoice, only: %i[show edit update destroy]
  before_action :set_services, only: %i[new edit]

  def create
    @invoice = Invoice.new(invoice_params)
    @invoice.user = current_user
    @invoice.build_period(period_params)
    if @invoice.save
      redirect_to invoices_path, notice: t('invoices.successful_save')
    else
      redirect_to new_invoice_path, alert: @invoice.errors.full_messages.join(', ')
    end
  end

  def show
    @service = @invoice.service
  end

  def update
    if @invoice.update(invoice_params)
      redirect_to invoices_path, notice: t('invoices.successful_update')
    else
      redirect_to invoice_path, alert: @invoice.errors.full_messages.join(', ')
    end
  end

  def destroy
    if @invoice.destroy
      redirect_to invoices_path, notice: t('invoices.successful_destroy')
    else
      redirect_to invoices_path, alert: @invoice.errors.full_messages.join(', ')
    end
  end

  def index
    @invoices = current_user.invoices
  end

  private

  def invoice_params
    params.require(:invoice).permit(
      :invoice_nr, :service_id, :user_id, :price, :comment
    )
  end

  def period_params
    params.require(:invoice).require(:period).permit(
      :period_start, :period_end, :single
    )
  end

  def set_invoice
    @invoice = Invoice.find(params[:id])
  end

  def set_services
    @services = Service.all
  end
end

app/views/invoices/_form.html.slim
= simple_form_for invoice, validate: true do |f|
  .row
    .column.small-12.medium-6
      = f.input :invoice_nr, label: t('invoices.invoice_nr')
      = f.association :service,
                label: t('services.title'),
                collection: services,
                prompt: t('invoices.select_service'),
                group_label_method: :name,
                group_method: :id
      = f.input :price, label: t('invoices.price')
      = f.input :comment, label: t('invoices.comment')
    .column.small-12.medium-6
      = f.association :period do |p|
        = p.input :period_start,
          as: :date,
          input_html: { value: beginning_of_last_month },
          html5: true,
          label: t('periods.period_start')
        = p.input :period_end,
          as: :date,
          input_html: { value: end_of_last_month },
          html5: true,
          label: t('periods.period_end'),
          required: false
        = p.input :single?, as: :boolean, label: t('periods.single')
  .row
    button.small(type='submit')= t('general.buttons.save')

app/views/invoices/edit.html.slim
- @title = t('invoices.edit')

= render 'form', invoice: @invoice, services: @services

.row
  .column.text-right
    = link_to invoice_path(@invoice),
      method: :delete,
      data: {confirm: t('general.destroy_confirmation')} do
        button.tiny.alert= t('general.buttons.destroy')

app/views/invoices/index.html.slim
- @title = t('general.titles.invoices_list')
.row
  .columns
    - if @invoices.present?
      table
        th
        th= t('services.title')
        th= t('invoices.invoice_nr')
        th= t('users.title')
        th= t('invoices.price')
        th= t('periods.title')
        th
        - c = 1
        - @invoices.each do |i|
          tr
            td= c
            td= i.service.name
            td= i.invoice_nr
            td= i.user.email
            td= i.price
            td= i.strf_period
            td= link_to invoice_path(i) do
              button.tiny.success= t('general.buttons.show')
          - c += 1
    - else
      h4= t('invoices.none_found')
    a.button.success.small(href="#{new_invoice_path}")= t('invoices.new')

app/views/invoices/new.html.slim
- @title = t('invoices.new')

= render 'form', invoice: Invoice.new, services: Service.all

app/views/invoices/show.html.slim
- @title = t('invoices.title')
.row
  .column.small-11.medium-5.square-box
    - if @invoice.invoice_nr.present?
      .row
        .column
          b= "#{t('invoices.invoice_nr')}: "
          = @invoice.invoice_nr
    .row
      .column
        b= "#{t('services.title')}: "
        = @service.name
    .row
      .column
        b= "#{t('invoices.price')}: "
        = @invoice.price
    - if @invoice.comment.present?
      .row
        .column
          b= "#{t('invoices.comment')}: "
          = @invoice.comment
    .row
      .column
        b= "#{t('general.attributes.created_at')}: "
        = l(@invoice.created_at)
  .column.small-11.medium-5.square-box
    .row
      .column
        h4= "#{t('periods.title')}:"
    .row
      - if @invoice.single?
        .column
          b= t('periods.single')
        .column
          b= "#{t('invoices.invoice_date')}:"
          = @invoice.period_start
      - else
        .column
          b= "#{t('periods.period_start')}: "
          = l(@invoice.period_start)
        .column
          b= "#{t('periods.period_end')}: "
          = l(@invoice.period_end)

.row
  .column
    = link_to edit_invoice_path do
      button.warning.small= t('general.buttons.edit')