config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'home#welcome', as: 'welcome'
  devise_for :users,
    class_name: 'FormUser',
    controllers: {
      omniauth_callbacks: 'omniauth_callbacks',
      registrations: 'registrations'
    }
  resources :users, only: %i[show index]
  resources :services
  resources :invoices
  resources :communities do
    resources :invitations, only: %i[new create show destroy]
    post 'join/:id', to: 'invitations#join', as: 'join'
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :omniauthable

  has_many :invoices
  has_many :identities
  has_many :partnerships
  has_many :communities
  has_many :invitations

  def full_name
    # TODO: migrate separate field to user, let user
    # also choose which names from identities he/she would
    # like to use
    identities.present? ? identities.first.name : "Ano Nymous"
  end

  def all_communities
    Community.where(id: partnerships.pluck(:community_id))
  end

  def facebook
    identities.where(provider: 'facebook').first
  end

  def facebook_client
    @facebook_client ||= Facebook.client(access_token: facebook.accesstoken)
  end

  def google_oauth2
    identities.where(provider: 'google_oauth2').first
  end

  def google_oauth2_client
    unless @google_oauth2_client
      @google_oauth2_client = Google::APIClient.new(
        application_name: 'hOverView',
        application_version: '1.0.0'
      )
      @google_oauth2_client.authorization.update_token!(
        access_token: google_oauth2.accesstoken,
        refresh_token: google_oauth2.refreshtoken
      )
    end
    @google_oauth2_client
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController

  def show
    @invitations = @user.invitations
  end

  def index
    @users = User.all
  end

end

app/views/users/index.html.slim
- @title = t('general.titles.users_list')
.row
  .column
    table.hover
      th
      th= t('users.email')
      th= t('users.created_at')
      - c = 1
      - @users.each do |u|
        tr
          td= c
          td= u.email
          td= u.created_at
        - c += 1

app/views/users/show.html.slim
- @title = @user.full_name
.row
  .column
    = "Email: #{@user.email}"
- if @invitations.present?
  .row
    .column
      h4= t('invitations.you_have_been_invited')
      table.hover
        th
        th= t('communities.name')
        th= t('communities.master')
        th= t('partnerships.share')
        th
        - c = 1
        - @invitations.each do |i|
          tr
            td= c
            td= i.community.name
            td= i.community.master.full_name
            td= i.share
            td= link_to community_join_path(i.community, i), method: :post do
                  button.tiny= t('invitations.join')
          - c += 1