config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'home#welcome', as: 'welcome'
  devise_for :users,
    class_name: 'FormUser',
    controllers: {
      omniauth_callbacks: 'omniauth_callbacks',
      registrations: 'registrations'
    }
  resources :users, only: %i[show index]
  resources :services
  resources :invoices
  resources :communities do
    resources :invitations, only: %i[new create show destroy]
    post 'join/:id', to: 'invitations#join', as: 'join'
  end
end

app/models/community.rb
# frozen_string_literal: true

class Community < ApplicationRecord
  has_many :partnerships, dependent: :destroy
  has_many :invitations, dependent: :destroy
  belongs_to :user, required: false

  validates :name, presence: true

  alias_attribute :master, :user

  def set_master(user)
    self.master = user
  end

  def master?(user)
    self.master == User.find(user.id)
  end

  def members
    self.partnerships.map { |p| p.user }
  end
end

app/controllers/communities_controller.rb
# frozen_string_literal: true

class CommunitiesController < ApplicationController
  before_action :set_community, only: %i[show edit update destroy]

  def create
    @community = Community.new(community_params)
    @community.set_master(current_user)
    partnership = current_user.partnerships.build(
      community: @community,
      share: 1
    )
    if partnership.save
      redirect_to communities_path, notice: t('communities.successful_create')
    else
      redirect_to new_community_path, alert: partnership.errors.full_messages.join(', ')
    end
  end

  def show
    @master = @community.master
    @partnerships = @community.partnerships
    @invitations = @community.invitations
  end

  def update
    if @community.update(community_params)
      redirect_to communities_path, notice: t('communities.successful_update')
    else
      redirect_to edit_community_path, alert: @community.errors.full_messages.join(', ')
    end
  end

  def destroy
    if @community.destroy
      redirect_to communities_path, notice: t('communities.successful_destroy')
    else
      redirect_to community_path(@community), alert: @community.errors.full_messages.join(', ')
    end
  end

  def index
    @communities = current_user.all_communities
  end

  private

  def community_params
    params.require(:community).permit(
      :name, :user
    )
  end

  def set_community
    @community = Community.find(params[:id])
  end
end

app/helpers/community_helper.rb
# frozen_string_literal: true

module CommunityHelper
  def percentify(arg)
    "#{(arg * 100).round}%"
  end

  def member_name(p)
    if p.user == p.community.master
      "#{p.user.full_name} (<b>#{t('communities.master')}</b>)".html_safe
    else
      p.user.full_name
    end
  end
end

app/views/communities/_form.html.slim
= simple_form_for community, validate: true do |f|
  .row
    .column.small-12.medium-6
      = f.input :name, label: t('communities.name')
  .row
    button.small(type='submit')= t('general.buttons.save')

app/views/communities/edit.html.slim
- @title = t('communities.edit')

= render 'form', community: @community

.row
  .column.text-right
    = link_to community_path(@community),
      method: :delete,
      data: { confirm: t('general.destroy_confirmation') } do
        button.tiny.alert= t('general.buttons.destroy')

app/views/communities/index.html.slim
- @title = t('general.titles.communities_list')
.row
  .column
    - if @communities.present?
      table
        th
        th= t('communities.name')
        th
        - c = 1
        - @communities.each do |cm|
          tr
            td= c
            td= cm.name
            td= link_to community_path(cm) do
              button.tiny.success= t('general.buttons.show')
          - c += 1
    - else
      h4= t('communities.none_found')
.row
  .column
    a.button.success.small(href="#{new_community_path}")= t('communities.new')

app/views/communities/new.html.slim
- @title = t('communities.new')

= render 'form', community: Community.new

app/views/communities/show.html.slim
- @title = "#{t('communities.title')} #{@community.name}"
.row
  .column
    h4= "#{t('communities.members')}:"
    table.hover
      th
      th= t('users.name')
      th= t('partnerships.added_at')
      th= t('partnerships.share')
      - c = 1
      - @partnerships.each do |p|
        tr
          td= c
          td= link_to member_name(p), user_path(p.user)
          td= l(p.created_at)
          td= percentify(p.share)
        - c += 1
.row
  .column
    - if @invitations.present?
      h4= "#{t('invitations.pending_invitations')}:"
      table.hover
        th
        th= t('users.email')
        th= t('invitations.share')
        th= t('invitations.invited_at')
        th
        - c = 1
        - @invitations.each do |i|
          tr
            td= c
            td= i.email
            td= percentify(i.share)
            td= l(i.created_at)
            td
              - if @community.master?(current_user)
                = link_to community_invitation_path(@community, i),
                          method: :delete,
                          data: { confirm: t('general.destroy_confirmation') } do
                            button.alert.tiny= t('invitations.revoke')
            - c += 1
    - else
      - if @community.master?(current_user)
        h4= t('invitations.no_invitations_yet')
    - if @community.master?(current_user)
      = link_to t('communities.invite_member'), new_community_invitation_path(@community)
.row
  .column
    = link_to edit_community_path do
      button.warning.small= t('general.buttons.edit')