config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'home#welcome', as: 'welcome'
  devise_for :users,
    class_name: 'FormUser',
    controllers: {
      omniauth_callbacks: 'omniauth_callbacks',
      registrations: 'registrations'
    }
  resources :users, only: %i[show index]
  resources :services
  resources :invoices
  resources :communities do
    resources :invitations, only: %i[new create show destroy]
    post 'join/:id', to: 'invitations#join', as: 'join'
  end
end

app/views/layouts/_messages.html.slim
- if notice
  p.alert-box.info= notice
- if alert
  p.alert-box.alert= alert

app/views/layouts/_navbar.html.slim
nav.top-bar role='navigation'
  ul.title-area
    li= link_to welcome_path do
      i.large.fi-home

  section.top-bar-section
    /! Left Nav Section
    ul.left
      li.divider
      li= link_to t('general.titles.users'), users_path
      li.divider
      li= link_to t('general.titles.services'), services_path
      li.divider
      li= link_to t('general.titles.invoices'), invoices_path
      li.divider
      li= link_to t('general.titles.communities'), communities_path

    /! Right Nav Section
    ul.right
      li= link_to @user.full_name, user_path(@user)
      li.divider
      li= link_to destroy_user_session_path, method: :delete do
        i.fi-power

app/views/layouts/_title.html.slim
- if @title.present?
  .row
    .column
      .panel
        h2= @title

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset='utf-8' name='viewport' content='width=device-width, initial-scale=1.0'
    title= content_for?(:title) ? yield(:title) : t('general.home')
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag \
      "https://www.gstatic.com/charts/loader.js",
      'vendor/modernizr',
      'application'
    = csrf_meta_tags
    = include_gon
    = Gon::Base.render_data
  body
    - if user_signed_in?
      = render 'layouts/navbar'
      = render 'layouts/title'
      = render 'layouts/messages'
      = yield
    - else
      .center
        h1= t('general.home')
      = render 'layouts/messages'
      .row
        .column
        .column.small-offset-0.small-12.medium-offset-1.medium-10.large-offset-3.large-6
          = yield
        .column